name: Sync gists

on:
  push:
    branches:
      - master
      - dev

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: update training core
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-training-core
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/jeanollion/4aea9bef9c4b98aa5f8084e1be5ed6ee
          gist_title: >
            ${{ github.ref == 'refs/heads/master' &&
               'training_core.py' ||
               'training_core_dev.py' }}
          gist_description: Core script for DL training
          github_file: training_scripts/training_core.py
      - name: update training DiSTNet2D
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-distnet2d
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/jeanollion/789b9dbbda92da548401c7250f1631ad
          gist_title: >
            ${{ github.ref == 'refs/heads/master' &&
               'training_distnet2d.py' ||
               'training_distnet2d_dev.py' }}
          gist_description: Training script for DiSTNet2D
          github_file: training_scripts/training_distnet2d.py
      - name: update training pixmclass
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-pixmclass
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/jeanollion/60ad55e49a69dbf08e337ce97b030ce5
          gist_title: >
            ${{ github.ref == 'refs/heads/master' &&
               'training_pixmclass.py' ||
               'training_pixmclass_dev.py' }}
          gist_description: Core script for DL training
          github_file: training_scripts/training_pixmclass.py
      - name: update training blissed
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-blissed
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/jeanollion/8ca51fc1449749b73d5064c9d28e53f4
          gist_title: >
            ${{ github.ref == 'refs/heads/master' &&
               'training_blissed.py' ||
               'training_blissed_dev.py' }}
          gist_description:  Training script for blissed (Blind Self Supervised Denoising)
          github_file: training_scripts/training_blissed.py
      - name: update predict
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync-predict
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/jeanollion/7b156bdbd7769f7a0a64b6774550ff4d
          gist_title: >
            ${{ github.ref == 'refs/heads/master' &&
               'predict.py' ||
               'predict_dev.py' }}
          gist_description: Predict script for DNN
          github_file: prediction_scripts/predict.py
